version: 2
updates:

  - package-ecosystem: "gitsubmodule"
    directory: "Fronter"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "commonItems"
    schedule:
      interval: "daily"
